"""003_add_verification_codes

Revision ID: 17e6ecb83046
Revises: e9d57ee8cc99
Create Date: 2026-09-04 12:30:42.189122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e6ecb83046'
down_revision: Union[str, Sequence[str], None] = 'e9d57ee8cc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_channel'), 'verification_codes', ['channel'], unique=False)
    op.create_index(op.f('ix_verification_codes_created_at'), 'verification_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_codes_expires_at'), 'verification_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_expires_at'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_created_at'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_channel'), table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
